version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    networks:
      - mynet

  whoami:
    image: traefik/whoami
    ports:
      - "8081:80"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
